In [1]:
import pandas as pd

In [2]:
expert_df = pd.read_csv("/home/luanagbmartins/Documents/CEIA/offline_to_online/CORL/data/results_expert.csv")
expert_df = expert_df[["env", "model", "episode_rewards_mean", "episode_rewards_std"]].groupby(["env", "model"]).mean().reset_index()
expert_df

                       env model  episode_rewards_mean  episode_rewards_std
0    G1JoystickFlatTerrain   PPO             33.677066             9.227532
1             Go2Footstand   PPO             19.425384             0.044671
2                 Go2Getup   PPO             17.535575             0.664115
3             Go2Handstand   PPO             19.169041             0.025577
4   Go2JoystickFlatTerrain   PPO             31.042490             1.871823
5  Go2JoystickRoughTerrain   PPO             29.736256             4.520527
6    H1InplaceGaitTracking   PPO             37.660809             3.146010
7   H1JoystickGaitTracking   PPO            163.611326            14.199276

In [3]:
offline_df = pd.read_csv("/home/luanagbmartins/Documents/CEIA/offline_to_online/CORL/data/results_offline.csv")
offline_df["dataset_level"] = offline_df["dataset_id"].apply(lambda x: x.split("-")[-2])
offline_df = offline_df[["env", "dataset_level", "command_type", "model", "episode_rewards_mean", "episode_rewards_std"]].sort_values(["env", "dataset_level"])
offline_df

,env,dataset_level,command_type,model,episode_rewards_mean,episode_rewards_std
1,Go2Getup,expert,NaN,BC,16.230384,1.676745
2,Go2Getup,medium,NaN,BC,10.313994,2.357308
4,Go2JoystickFlatTerrain,expert,foward,BC,25.219328,8.498934
5,Go2JoystickFlatTerrain,expert,fowardfixed,BC,22.933115,9.125286
0,Go2JoystickFlatTerrain,medium,fowardfixed,BC,20.585751,9.335407
3,Go2JoystickFlatTerrain,medium,foward,BC,20.397867,11.213778

In [4]:
random_df = pd.read_csv("/home/luanagbmartins/Documents/CEIA/offline_to_online/CORL/data/results_random.csv")
random_df = random_df[["env", "model", "episode_rewards_mean", "episode_rewards_std"]].groupby(["env", "model"]).mean().reset_index()
random_df["dataset_level"] = "random"
random_df

,env,model,episode_rewards_mean,episode_rewards_std,dataset_level
0,Go2Footstand,random,0.995735,0.622157,random
1,Go2Getup,random,0.240458,0.120450,random
2,Go2Handstand,random,1.007123,0.785533,random
3,Go2JoystickFlatTerrain,random,0.000461,0.001382,random
4,Go2JoystickRoughTerrain,random,0.002157,0.004369,random

In [5]:
combined_df = pd.concat([expert_df, random_df, offline_df], ignore_index=True)
combined_df = combined_df.sort_values(["env", "dataset_level"])
combined_df

,env,model,episode_rewards_mean,episode_rewards_std,dataset_level,command_type
0,G1JoystickFlatTerrain,PPO,33.677066,9.227532,NaN,NaN
8,Go2Footstand,random,0.995735,0.622157,random,NaN
1,Go2Footstand,PPO,19.425384,0.044671,NaN,NaN
13,Go2Getup,BC,16.230384,1.676745,expert,NaN
14,Go2Getup,BC,10.313994,2.357308,medium,NaN
9,Go2Getup,random,0.240458,0.120450,random,NaN
2,Go2Getup,PPO,17.535575,0.664115,NaN,NaN
10,Go2Handstand,random,1.007123,0.785533,random,NaN
3,Go2Handstand,PPO,19.169041,0.025577,NaN,NaN
15,Go2JoystickFlatTerrain,BC,25.219328,8.498934,expert,foward
16,Go2JoystickFlatTerrain,BC,22.933115,9.125286,expert,fowardfixed
17,Go2JoystickFlatTerrain,BC,20.585751,9.335407,medium,fowardfixed
18,Go2JoystickFlatTerrain,BC,20.397867,11.213778,medium,foward
11,Go2JoystickFlatTerrain,random,0.000461,0.001382,random,NaN
4,Go2JoystickFlatTerrain,PPO,31.042490,1.871823,NaN,NaN
12,Go2JoystickRoughTerrain,random,0.002157,0.004369,random,NaN
5,Go2JoystickRoughTerrain,PPO,29.736256,4.520527,NaN,NaN
6,H1InplaceGaitTracking,PPO,37.660809,3.146010,NaN,NaN
7,H1JoystickGaitTracking,PPO,163.611326,14.199276,NaN,NaN

In [8]:
combined_df[combined_df["env"] == "Go2JoystickFlatTerrain"].sort_values(["command_type", "dataset_level"])

,env,model,episode_rewards_mean,episode_rewards_std,dataset_level,command_type
15,Go2JoystickFlatTerrain,BC,25.219328,8.498934,expert,foward
18,Go2JoystickFlatTerrain,BC,20.397867,11.213778,medium,foward
16,Go2JoystickFlatTerrain,BC,22.933115,9.125286,expert,fowardfixed
17,Go2JoystickFlatTerrain,BC,20.585751,9.335407,medium,fowardfixed
11,Go2JoystickFlatTerrain,random,0.000461,0.001382,random,NaN
4,Go2JoystickFlatTerrain,PPO,31.042490,1.871823,NaN,NaN